repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.4
  hooks:
  - id: autopep8
- repo: https://github.com/PyCQA/isort
  rev: '5.6.4'
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: '20.8b1'
  hooks:
  - id: black
    language_version: python3 # Should be a command that runs python3.6+
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.15.1
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: requirements-txt-fixer
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-typing-imports==1.1.0]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
